development:
  adapter: postgresql
  database: rspec_rails_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: rspec_rails_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: rspec_rails
  pool: 5
  timeout: 5000