development:
  adapter: postgresql
  host: localhost
  username:
  password:
  database: sf_rspec_rails_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  host: localhost
  username:
  password:
  database: sf_rspec_rails_test
  pool: 5
  timeout: 5000