source 'https://rubygems.org'

gem 'rails', '3.2.12'
gem "pg"

group :test, :development do
  gem "rspec-rails", "~> 2.0"
end

group :test do
  gem 'capybara'
  gem 'selenium-webdriver', '~> 2.35.0'
  gem 'database_cleaner'
  gem 'factory_girl_rails'
  gem 'faker'
end
